### ISSUE TITLE
help please, somehow unlinked from installfest

### ISSUE THREAD

**Issue by amadeot** [teamattendance/attendance_tracker_app#44]
@phlco @annarankin @sungchoi  

are any instructors on campus today? I was trying to set env variables, got stuck in a weird area by hitting enter after autofilling the wrong thing, and think I undid the entire installfest by accident. no idea what to do.

related: the error says:

Last login: Sat Dec 19 14:31:14 on ttys000
-bash: /Users/amadeot/.bash_profile: line 169: syntax error near unexpected token <<<' -bash: /Users/amadeot/.bash_profile: line 169:<<<<<<< HEAD'

instead of the normal login script. also now it's saying my computer name is

Maxs-MacBook-Air-2:

and i'm pretty sure it's supposed to be Max-MacBook-Air. Maybe that's the issue but don't know

**Comment by amadeot** [comment]
I think it's definitely the bit related to how my computer name, I found this guide:

http://apple.stackexchange.com/questions/30552/os-x-computer-name-not-matching-what-shows-on-terminal

but I'm really afraid to mess with these settings without someone here.

**Comment by annarankin** [comment]
Hey Amadeo, can you tell us step by step what commands you entered and what
files you modified? Also, please paste in your bash profile!

**Comment by amadeot** [comment]
So I was trying to get to my .bash_profile, typed .bas and hit tab, thinking it'd autocomplete to it, but it autocompleted to something else. I hit enter before looking at it, and it had some huge list of something I wasn't able to get out of. I pressed ctrl+c, trying to get out of it, and there was a prompt that said something about installfest. I stupidly panicked and exited out of the window, so I'm not sure how to see what it said or what file I ended up in. I kept working, didn't notice anything wrong until I needed to rake, and it said it didn't know what rake was.

Can I slack it to you? I thought I shouldn't paste the whole bash profile in public

**Comment by phlco** [comment]
It looks like you have a merge conflict in your bash profile from the looks of this: `:<<<<<<< HEAD`

Has this been resolved?

**Comment by amadeot** [comment]
not yet resolved. i checked the bash history at anna's suggestions via slack just now but didn't see anything that looked weird.

**Comment by amadeot** [comment]
getting kicked out of GA but I'll be back again trying to solve this when i get home

**Comment by phlco** [comment]
can you open your bash profile in sublime?

```
subl ~/.bash_profile
```

if you cant open it because of the terminal problems you can try it via the GUI with finder and text edit
